# Generated by Django 2.1.1 on 2019-11-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotiseria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('puede_crear_producto', 'Crear prod'),)},
        ),
    ]
