# Generated by Django 2.2 on 2019-11-22 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotiseria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
