# Generated by Django 2.1.1 on 2019-10-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotiseria', '0002_pedidoproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
