# Generated by Django 2.1.1 on 2019-11-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotiseria', '0002_auto_20191125_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('es_admin', 'Es_Admin'),)},
        ),
    ]
