# Generated by Django 2.1.1 on 2019-11-25 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotiseria', '0003_auto_20191125_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('es_admin', 'Es_Admin'), ('es_repart', 'Es_Repart'), ('es_recep', 'Es_Recep'))},
        ),
    ]
