# Generated by Django 2.1.1 on 2019-10-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotiseria', '0004_auto_20191004_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.IntegerField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
